### PR TITLE
modify logger debug info

### PR DESCRIPTION
**Pull request by fluency03**
@logger.debug("Couldn't generate protobuf: ${e}")

to 

@logger.debug("Couldn't generate protobuf: #{e.inspect}")

### CODE REVIEW

**Comment by IngaFeick** [comment]
@fluency03 would you mind signing the elasticsearch CLA? It's required for pull requests. 
More information can be found here: https://www.elastic.co/contributor-agreement
Thank you!

**Comment by fluency03** [comment]
signed it

**Comment by fluency03** [comment]
why I am not passing the CI check? just changed the logger message

**Comment by IngaFeick** [comment]
I am closing this PR because the same change is already done in https://github.com/logstash-plugins/logstash-codec-protobuf/pull/18 and has been merged from there.

**Pull request closed without merging**
