### PR TITLE
Add type converter to protobuf encoder

### PR DESCRIPTION
**Pull request by IngaFeick**
Change 1: 
The protobuf encoder library is very strict with regards to data types. Example: an event has an integer field but the protobuf definition expects a float. This would lead to an exception and the event would be lost. 
This feature tries to convert the datatypes to the expectations of the protobuf definitions, without modifying the data whatsoever. Examples of conversions it might attempt:
"true" string => true boolean
17 int => 17.0 float
12345 number => "12345" string

Change 2:
When misconfigured (missing imports of nested references), the protobuf class loading mechanism would log an error message but not stop the pipeline, which led to nullpointer exceptions further down the line when the encoder tried to access the unavailable classes. We have changed this behaviour to raise an exception and stop the pipeline when any of the needed protobuf classes is not loadable.

### CODE REVIEW

**Comment by hugobally** [comment]
Hi, I'd like to use your codec but when I try to encode a double I get a type error exception. From what I understand the double is cast to a string and protobuf crashes. This PR seems to fix the bug, do you have any estimation for when it will get merged ? Or is there a workaround I'm missing ? Thank you for your work and help.

**Comment by IngaFeick** [comment]
Hi @hugobally I am planing to merge this within the next couple of days, if nobody objects. What you could do as a workaround until then is to manually typecast the fields which are causing problems, using the mutate > convert filter.

**Comment by hugobally** [comment]
Thanks I'll wait for the merge then 👍

**Comment by IngaFeick** [comment]
@hugobally 1.2.2 is released to rubygems, please let me know how it works for you :)

**Comment by hugobally** [comment]
@IngaFeick It's working as expected, thanks !

**Comment by IngaFeick** [comment]
@hugobally happy to hear, thanks for the feedback!

**Pull request merged**
